version: latest
services:
  app:
    build:
     context: .
     dockerfile:  Docker
  ports:
    - 8080:8080
    
  
  depends_on:
    - db
  environment:
    - SQLALCHEMY_DATABASE_URI=sqlite:///data.db
    - SQLALCHEMY_TRACK_MODIFICATIONS=FALSE
    
  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresq1/data
    environment:
      - POSTGRES_USER=jannette
      - POSTGRESS_DB=databasejannette
  
      
  
  nginx:
    image: nginx:alpine
    ports:
    - 80:80
  
      
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.con
    depends_on:
     - app

   
