version: latest
services:
flask-app:
  build: .
  ports:
    - 8080:8080
  depends_on:
    - db
  environment:
    - SQLALCHEMY_DATABASE_URI=sqlite:///data.db
    - SQLALCHEMY_TRACK_MODIFICATIONS=FALSE
    
  db:
    image: postgres:latest
    volumes:
      - ./data:/var/lib/postgresq1/data
    environment:
      - POSTGRES_USER=jannette
      - POSTGRESS_DB=databasejannette
  
      
  
  nginx:
    image: nginx:alpine
    ports:
    - target: 80
      protocol: tcp
      
    volumes:
    - type: bind
      source: ./nginx.conf
      target: /etc/nginx/nginx.con
    depends_on:
      app

   
